tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d

ports:
  - port: 5432
    onOpen: ignore
  - port: 8081
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker